apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment

spec: # specification for deployment
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec: # specification for pod
      containers:
        - name: nginx
          image: nginx:1.16
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          ports:
            - containerPort: 80
